export const galleryData = [
  {
    id: 1,
    name: 'Still Life with Pears',
    size: '8" x 10"',
    medium: 'Oil on canvas',
    fileName: "pears.webp",
  },
  {
    id: 2,
    name: 'Wonderment',
    size: '18" x 24"',
    medium: 'Oil on canvas',
    fileName: "wonderment.webp",
  },
  {
    id: 3,
    name: 'Flight Take Off',
    size: '24" x 36"',
    medium: 'Oil on canvas',
    fileName: "flighttakeoff.webp",
  },
  {
    id: 4,
    name: 'Ladybugs',
    size: '10" x 12"',
    medium: 'Oil on canvas',
    fileName: "ladybugs.webp",
  },
  {
    id: 5,
    name: 'Wild Freedom',
    size: '18" x 24"',
    medium: 'Oil on canvas',
    fileName: "wildfreedom.webp",
  },
  {
    id: 6,
    name: 'Morning Flight',
    size: '36" x 48"',
    medium: 'Oil on canvas',
    fileName: "morningflight.webp",
  },
  {
    id: 7,
    name: 'Grandfather',
    size: '10" x 12"',
    medium: 'Oil on canvas',
    fileName: "grandfather.webp",
  },
  {
    id: 8,
    name: 'Summer Lake',
    size: '8" x 10"',
    medium: 'Oil on canvas',
    fileName: "summerlake.webp",
  },
  {
    id: 9,
    name: 'Summer Chores',
    size: '36" x 36"',
    medium: 'Oil on canvas',
    fileName: "summerchores.webp",
  },
  {
    id: 10,
    name: 'Country Hills',
    size: '16" x 20"',
    medium: 'Oil on canvas',
    fileName: "countryhills.webp",
  },
  {
    id: 11,
    name: 'Summer Fields',
    size: '24" x 36"',
    medium: 'Oil on canvas',
    fileName: "summerfields.webp",
  },
  {
    id: 12,
    name: 'Deck View',
    size: '8" x 10"',
    medium: 'Oil on canvas',
    fileName: "deckview.webp",
  },
];