export const galleryData = [
  {
    id: 1,
    name: 'Still Life with Pears',
    size: '8" x 10"',
    medium: 'Oil on canvas',
    fileName: "pears.webp",
  },
  {
    id: 2,
    name: 'Flight Take Off',
    size: '24" x 36"',
    medium: 'Oil on canvas',
    fileName: "flighttakeoff.webp",
  },
  {
    id: 3,
    name: 'Wild Freedom',
    size: '18" x 24"',
    medium: 'Oil on canvas',
    fileName: "wildfreedom.webp",
  },
  {
    id: 4,
    name: 'Summer Lake',
    size: '8" x 10"',
    medium: 'Oil on canvas',
    fileName: "summerlake.webp",
  },
  {
    id: 5,
    name: 'Morning Flight',
    size: '36" x 48"',
    medium: 'Oil on canvas',
    fileName: "morningflight.webp",
  },
  {
    id: 6,
    name: 'Grandfather',
    size: '10" x 12"',
    medium: 'Oil on canvas',
    fileName: "grandfather.webp",
  },
  {
    id: 7,
    name: 'Summer Chores',
    size: '36" x 36"',
    medium: 'Oil on canvas',
    fileName: "summerchores.webp",
  },
  {
    id: 8,
    name: 'Country Hills',
    size: '16" x 20"',
    medium: 'Oil on canvas',
    fileName: "countryhills.webp",
  },
  {
    id: 9,
    name: 'Summer Fields',
    size: '24" x 36"',
    medium: 'Oil on canvas',
    fileName: "summerfields.webp",
  },
  {
    id: 10,
    name: 'Deck View',
    size: '8" x 10"',
    medium: 'Oil on canvas',
    fileName: "deckview.webp",
  },
  {
    id: 11,
    name: 'Wonderment',
    size: '18" x 24"',
    medium: 'Oil on canvas',
    fileName: "wonderment.webp",
  },
  {
    id: 12,
    name: 'Deer in the Mist',
    size: '24" x 36"',
    medium: 'Oil on canvas',
    fileName: "deer.jpeg",
  },
  {
    id: 13,
    name: 'First Blooms',
    medium: 'Oil on canvas',
    fileName: "blooms.jpeg",
  },
  {
    id: 14,
    name: 'Forest Symphony',
    medium: 'Oil on canvas',
    fileName: "symphony.jpeg",
  },
  {
    id: 15,
    name: 'Talk by the brick wall',
    medium: 'Oil on canvas',
    fileName: "talk.jpeg",
  },
  {
    id: 16,
    name: 'Ukelele',
    size: '16" x 20"',
    medium: 'Oil on canvas',
    fileName: "ukelele.jpeg",
  },
  {
    id: 17,
    name: 'Still Life at 3:33',
    medium: 'Oil on canvas',
    fileName: "stilllife.jpeg",
  },
  {
    id: 18,
    name: 'Horse at Sunset',
    medium: 'Oil on canvas',
    fileName: "sunsethorse.jpeg",
  },
  {
    id: 19,
    name: 'Winter',
    medium: 'Oil on canvas',
    fileName: "winter.jpeg",
  },
  {
    id: 20,
    name: 'Gallop',
    medium: 'Oil on canvas',
    fileName: "gallop.jpeg",
  },
  {
    id: 21,
    name: 'Cave',
    medium: 'Oil on canvas',
    fileName: "cave.jpeg",
  },
  {
    id: 22,
    name: 'Spirit, Wisdom, and Innocence',
    medium: 'Oil on canvas',
    fileName: "wisdom.jpeg",
  },
  {
    id: 23,
    name: 'Forest Concerto for Hemlocks and a Stream in Sun Major',
    size: '48" x 24"',
    medium: 'Oil on canvas',
    fileName: "concerto.jpeg",
  },
  {
    id: 24,
    name: 'Farmer and Cows',
    medium: 'Oil on canvas',
    fileName: "cows.jpeg",
  },
  {
    id: 25,
    name: 'Conversation on the old tree',
    medium: 'Oil on canvas',
    fileName: "conversation.jpeg",
  },
  {
    id: 26,
    name: 'Conversation on the old tree',
    medium: 'Oil on canvas',
    fileName: "conversation.jpeg",
  },
  {
    id: 27,
    name: 'Horse in the Sun',
    size: '16" x 20"',
    medium: 'Oil on canvas',
    fileName: "horse.jpeg",
  },
  {
    id: 28,
    name: 'Tolliver Falls',
    size: '60" x 48"',
    medium: 'Oil on canvas',
    fileName: "falls.jpeg",
  },
  {
    id: 29,
    name: 'Jump',
    size: '24" x 24"',
    medium: 'Oil on canvas',
    fileName: "jump.jpeg",
  },
  {
    id: 30,
    name: 'Sleepy Hollow Farm',
    medium: 'Oil on canvas',
    fileName: "farm.jpeg",
  },
  {
    id: 31,
    name: 'Bald Eagle',
    medium: 'Oil on canvas',
    fileName: "eagle.jpeg",
  },
  {
    id: 32,
    name: 'Home Sweet Home',
    medium: 'Oil on canvas',
    fileName: "home.jpeg",
  },
  {
    id: 33,
    name: 'Bird',
    size: '20" x 20"',
    medium: 'Oil on canvas',
    fileName: "bird.jpeg",
  },
  {
    id: 34,
    name: 'Aunt Agatha',
    size: '12" x 24"',
    medium: 'Oil on canvas',
    fileName: "auntagatha.jpeg",
  },
  {
    id: 35,
    name: 'Candle',
    medium: 'Oil on canvas',
    fileName: "candle.jpeg",
  },
  {
    id: 36,
    name: 'Ladybugs',
    medium: 'Oil on canvas',
    fileName: "ladybugs.jpeg",
  },
  {
    id: 37,
    name: 'Snow Fox',
    size: '9" x 12"',
    medium: 'Oil on canvas',
    fileName: "snowfox.jpeg",
  },
];